version: "3"

services:
  server:
    container_name: serv
    build: 
      context: server/
    networks:
      - mynetwork

  nginx:
    image: nginx:latest
    ports:
      - "80:8080"
    networks:
      - mynetwork
    links:
      - server
    depends_on:
      - server
    volumes:
      - ./volumes/nginx/nginx.conf:/etc/nginx/nginx.conf

networks:
  mynetwork: